In [1]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [2]:
a = int(input("Enter a: "))
b = int(input("Enter b: "))
print("Sum:",a+b)

Enter a:  2
Enter b:  3


Sum: 5


In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [6]:
a = np.array(60)
print(a)
print(a.ndim)
print(type(a))

60
0
<class 'numpy.ndarray'>


In [7]:
b = np.array([1,2,3,4])
print(b)
print(b.ndim)
print(type(b))


[1 2 3 4]
1
<class 'numpy.ndarray'>


In [9]:
c = np.array([[1,2,3,4],[1,2,3,4]])
print(c)
print(c.ndim)
print(type(c))

[[1 2 3 4]
 [1 2 3 4]]
2
<class 'numpy.ndarray'>


In [10]:
d = np.array([[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]])
print(d)
print(d.ndim)
print(type(d))

[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]
3
<class 'numpy.ndarray'>


In [13]:
d = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]],
              [[1,2,3,4],[1,2,3,4],[1,2,3,4]],
              [[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(d)
print(d.ndim)
print(type(d))

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3
<class 'numpy.ndarray'>


In [14]:
a = [1,2,3,4]
b = [5,6,7,8]
print(a+b)

[1, 2, 3, 4, 5, 6, 7, 8]


In [16]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a+b)

[ 6  8 10 12]


In [17]:
c = np.sum(a)
print(c)

10


In [18]:
d = np.sum(b)
print(d)

26


In [20]:
e = np.mean(a)
print(e)

2.5


In [21]:
f = np.mean(b)
print(f)

6.5


In [22]:
x = np.array([1,3.4,"yaswanth",6+9j,True,False])
print(x)
print(type(x))

['1' '3.4' 'yaswanth' '(6+9j)' 'True' 'False']
<class 'numpy.ndarray'>
